### ISSUE TITLE
Strigi cannot be installed: conflicts with existing /usr/lib64/ directory

### ISSUE THREAD

**Issue by FredBezies** [fluxer/katana#16]
Simple issue to reproduce.

After I built strigi, I got an error telling me package cannot be installed because some files are trying to be written in the wrong place: /usr/lib64 is existing. See attached screenshot.

![virtualbox_archlinux trinity_08_01_2019_11_20_26](https://user-images.githubusercontent.com/8571419/50824872-f8371800-1337-11e9-9c9c-6549b21f0b6b.png)

**Comment by fluxer** [comment]
Unfortunately I do not have x86_64 Arch setup to test it on at the moment but I think the solution would be to build it with LIB_DESTINATION set to /usr/lib since /usr/lib64 is symlink on Arch and /usr/lib is actual directory. I will try to push a fix as soon as I can test it.

**Comment by fluxer** [comment]
Thanks for reporting the issue.
