### ISSUE TITLE
Archlinux packaging: getting cleaner and shorter version in package name?

### ISSUE THREAD

**Issue by FredBezies** [fluxer/katana#20]
Hello.

I was looking at ariya-icons pgkver.

With default pkgver function, we have this: ariya-icons-4.18.0.54ae81b0-1-any.pkg.tar.xz

You can have something more informative. For example using this pkgver tagging:

`printf "4.18.0.r%s" "$(git rev-list --count HEAD)"`

You have: ariya-icons-4.18.0.r21-1-any.pkg.tar.xz

Don't you think it is cleaner to see how much commits are made, and it could be better for debugging.

Just a suggestion.

**Comment by fluxer** [comment]
I would love to include the full (long) hash of the commit actually but I doubt that's common practise by packagers for Arch and it may be a bit too long for a version too. Since you use Arch more than me and you have write access to the repo you can change it to be the revision count, I do not mind such change. I am glad you asked tho.

Cheers!

**Comment by FredBezies** [comment]
I think rXX will be more readable than a commit reference.

Only drawback: some rebuilt packages will be considered as older when installing them, but only once.

Will rebuild all packages and copy a list in this comment to show what it could look like.

**Comment by fluxer** [comment]
Looks good and some AUR packages include the model you suggested too so I approve.

**Comment by FredBezies** [comment]
So my pull request will be merged, I think :smiley:

**Comment by fluxer** [comment]
Yes, merged it.

**Comment by FredBezies** [comment]
Can I merge automatically updated PKGBUILD generated in a VirtualMachine? And fix a little typo in l10n PKGBUILD?

**Comment by fluxer** [comment]
Ofcourse! Feel free to make any changes without asking me, I will try to review the changes and we can discuss them on commit bases if necessary since GitHub provides the feature.

Cheers!

**Comment by FredBezies** [comment]
Upcoming "renames" applied within an hour.

strigi: 0.8.0.r15.b3754c6
katanalibs: 4.18.0.r1114.a6ed9873
katana-baseapps: 4.18.0.r328.2198cc4
katana-workspace: 4.18.0.r678.0c7124a1
qimageblitz: 0.0.7.r15.ee7b348
liblastfm-qt4: 1.0.9.r644.2ce2bfe
libmygpo-qt4: 1.1.0.r287.ba5db4d
katana-extraapps: 4.18.0.r546.3f656312
katana-l10n: 4.18.0.r91.31fe99e41

**Comment by FredBezies** [comment]
All PKGBUILDs are modified. Closing this bug.

**Comment by fluxer** [comment]
Awesome, cheers!
