### ISSUE TITLE
Cannot build qjson with katie

### ISSUE THREAD

**Issue by FredBezies** [fluxer/katana#23]
I don't know if there is an option for this package, but I cannot get it build:

```
==> Starting build()...
CMake Deprecation Warning at CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Qt5 not found, searching for Qt4
CMake Error at /usr/share/cmake-3.16/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.14.1" from /usr/bin/qmake, this code
  requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:65 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```

**Comment by fluxer** [comment]
There is no option for it, Katie has support for JSON format which is used in [Kate](https://github.com/fluxer/kde-baseapps/blob/master/kate/addons/kate/project/kateproject.cpp#L32) for an example.

If you require it for projects other than Katana I can make the required changes (if any) and add the option for you.

Cheers!

**Comment by FredBezies** [comment]
Did not know Katie support json by itself. Thanks for the info. Building katana-baseapps with katie right now.

Thanks for the info.

**Comment by fluxer** [comment]
No problem!

Cheers!

**Comment by fluxer** [comment]
Marked as TODO since it is require by kde-extraapps but will not be once the transition to Katie is complete.

**Comment by fluxer** [comment]
No packages depend on QJSON anymore.
