### ISSUE TITLE
Piracy seen on screenshots

### ISSUE THREAD

**Issue by falkTX** [fluxer/katana#27]
This is awkward..

I am quite sure the videos you have shown on many screenshots come from illegal sources.
Just as an example https://github.com/fluxer/katana/blob/master/screenshots/prototype-media-preview-in-file-properties.png

Would be nice to not promote such practices, keep those for yourself only please.
It gives a bad name to opensource software and culture.
We want companies and people to respect licenses (like the GPL), so let's do our part and respect them too.
Thanks

**Comment by dromer** [comment]
Just use one of the blender project open movies to make such screenshots.

Material like Big Buck Bunny or Sintel: https://en.wikipedia.org/wiki/Blender_(software)#Open_projects

**Comment by fluxer** [comment]
I work with examples in many formats to test and verify that whatever is parsing them (say XPM) works as expected. There is, for example, trademark in the runners.ppm image (https://github.com/fluxer/katie/tree/master/tests/benchmarks/gui/image/qimagereader/images) which someone may say is promotion but I doubt many care about that.

**Comment by fluxer** [comment]
It is also present in the qtbase repo: https://github.com/qt/qtbase/blob/dev/tests/benchmarks/gui/image/qimagereader/images/runners.ppm.

**Comment by falkTX** [comment]
Sorry I do not see how that is related

**Comment by fluxer** [comment]
It's not a license issues. I can rip personal DVD and show it off on screenshot.

**Comment by falkTX** [comment]
sure, backups are completely legal, at least in europe.
this is obviously not the case here though.

**Comment by fluxer** [comment]
If you do not like it take it to those who does such things. We will not solve that issue here.

**Comment by falkTX** [comment]
you are the one that is showing off your own usage of movie piracy within your project screenshots.
I am sorry but this is really nasty.

kindly asking you to remove them, please.

**Comment by fluxer** [comment]
If you make screenshots yourself that show off the same features on the screenshots you want me to remove I will consider them.

**Comment by falkTX** [comment]
you do not see an issue with this at all? this is really surprising... it implies you are fine with breaking copyright law, please don't.

**Comment by fluxer** [comment]
I can tell what the issues is but it is broader than this project.

**Comment by falkTX** [comment]
do as you wish, but this is quite problematic for a lot of people.
and I am quite sure this is against GitHub's ToS...

**Comment by fluxer** [comment]
I have no clue honestly, contact them if you wish and see what they tell you.

**Comment by falkTX** [comment]
https://docs.github.com/en/github/site-policy/github-terms-of-service#c-acceptable-use

> Your use of the Website and Service must not violate any applicable laws, including **copyright or trademark laws**, export control or sanctions laws, or other laws in your jurisdiction.

It is quite clear actually

**Comment by fluxer** [comment]
The screenshots are no illegal, they are not copyrighted material. They are not even cover of the movie that is on the screenshot.

**Comment by falkTX** [comment]
Those screenshots **are** copyrighted material, what you could argue is they are fair-use, but considering you got them from piracy sources/illegal methods that won't help you much.

Quite appalled by this to be honest.
Do you expect others to respect your code/work license if you do not respect the license and laws of others?

**Comment by fluxer** [comment]
The screenshots are public domain license at best, made by me. I have not attached any license to them and people can do as the see fit with them.

No, I do not expect people to obey the rules of whatever license I have attached to any content I have produced be it in C++ source code or any other form. Piracy is not a fair trade and we will not stop it by ranting about it. Provide replacement for the screenshots you find offending or do not bother. That's all I have to say about it.

**Comment by dromer** [comment]
It's not the screenshot themselves as to what they contain:
This annotated content both incriminates anyone handling your project and violates direct copyright law (copy, you know the content you copied into your screenshot).

![](https://i.imgur.com/k8qUpWm.png)

Just use public domain content for your project expose.

**Comment by falkTX** [comment]
nice, just ignore the issue then :facepalm:
