### ISSUE TITLE
Konsole have text problems

### ISSUE THREAD

**Issue by longhorn8x** [fluxer/katana#29]
konsole needs to be calbrated so that you can see what your inserting better

**Comment by fluxer** [comment]
Yes, it does. I managed to narrow it down to the fixed fonts settings. So far what I know is that after changing any font settings from the system settings the issue disappears. Don't know what exactly is causing it but it should be fixed soon.

**Comment by fluxer** [comment]
Thanks for reporting the issue! Feel free to reopen if you are still experiencing it.
