### ISSUE TITLE
get effects like blur back

### ISSUE THREAD

**Issue by codic12** [fluxer/katana#32]
Hi, Katana is awesome! kde 4 was truly a glorious desktop. However, I've noticed that some of the awesome default desktop effects have been removed, such as blur. is it possible to restore these? could I simply compile some specific kwin modules (if so, can you point me to which ones that were removed?) or do I have to revert the changes to katana and recompile?

**Comment by codic12** [comment]
Also, what about applets like the kde4 networkmanager one?

**Comment by fluxer** [comment]
Hello, the blur effect was removed long ago so it will require great effort to revert the changes and make it functional again. It may be possible to write new effect that blurs and does not require OpenGL. Using [diminactive](https://github.com/fluxer/kde-workspace/tree/master/kwin/effects/diminactive) effect as starting point and setting the `_NET_WM_WINDOW_OPACITY` atom on inactively windows for example. Currently it can be achieved without effect via `xwininfo` and `xprop` commands but that is a bit tricky to automate probably. If you can write effect for and make pull request I will happily test and merge it.

About the applets, I was thinking about writing ConnMan/NetworkManager applet a few days ago, checked the D-Bus API yesterday too and it may be possible to write applet that offers basic functionality (such as choosing which network connection to use, disable and enable all network connections) depending which is available on the system. I am also considering to add PulseAudio support back to KMix but I right now I am focusing on fixing some issues such as Plasma desktop crashes on OpenBSD and on the upcomming FreeBSD 13.1 so it may take a while before I can take a deeper look into it.

**Comment by codic12** [comment]
> Hello, the blur effect was removed long ago so it will require great effort to revert the changes and make it functional again. It may be possible to write new effect that blurs and does not require OpenGL. Using [diminactive](https://github.com/fluxer/kde-workspace/tree/master/kwin/effects/diminactive) effect as starting point and setting the _NET_WM_WINDOW_OPACITY atom on inactively windows for example. Currently it can be achieved without effect via xwininfo and xprop commands but that is a bit tricky to automate probably. If you can write blur effect and make pull request I will happily test and merge it.

I see. Is there a reason why it has to not be dependent on opengl? Also, does katana retain api compatibility so I can compile some of the applets from https://github.com/KDE/kdeplasma-addons/tree/KDE/4.14, or will I have to change them? (no problem doing that, but then I can make a fork of that repository's 4.14 branch)

**Comment by fluxer** [comment]
Preferable, it should be XCB dependent since the KWin compositor is using XCB and the effect will be coded mostly around X11 atom. Using OpenGL will require bringing back the OpenGL KWin compositor which is will complicate things.

Katana does retain some of the API compatibility. The applets from 4.14 may require minor changes such as headers inclusions adjustments to build but the Plasma API remains mostly unchanged so some may work however some require libraries, applications or data engines which are not maintained as part of Katana and as such the news applet will not work for example.

**Comment by fluxer** [comment]
The `macro_log_feature` macro was removed, `set_package_properties` is used instead since it is standard CMake macro.

**Comment by codic12** [comment]
> Preferable, it should be XCB dependent since the KWin compositor is using XCB and the effect will be coded mostly around X11 atom. Using OpenGL will require bringing back the OpenGL KWin compositor which will complicate things.

I see, kwin is using xcb directly for compositing instead of going through any gpu libraries? that is very impressive...

**Comment by codic12** [comment]
Looks like I have my answers now, and seems that with a bit of effort I can get most of the 4.14 applets to compile, as well as some kde 4 software from back in the day. Thanks for your awesome work on this project!

**Comment by fluxer** [comment]
KWin is impressive indeed. There is a lot code for decorations, effects and other neat things.

It is possible, yes.

Thank you too!

**Comment by fluxer** [comment]
It appears there is a KWin application setting for opacity and shortcuts can be used to set window opacity btw, if you want to blur some windows it is possible as is now too:
<a href="https://ibb.co/Gkd169b"><img src="https://i.ibb.co/bL6y0F8/NET-WM-WINDOW-OPACITY.png" alt="NET-WM-WINDOW-OPACITY" border="0" /></a>
