### ISSUE TITLE
Second Monitor Doesn't Have The Option To Change The Background And/Or Display The Primary's Monitor Background

### ISSUE THREAD

**Issue by erievs** [fluxer/katana#41]
This is a feature of KDE-4 since I used to use it until around 2021/2020 in a dual monitor setup and I have never had an issue with have the non-primary monitor not having the option to change background and/or not displaying the main monitor's background. 

Debian 12, Latest Build of Katana as of 4/8/2023

How To Get The Issue:

Have two monitors, you will notice if you right-click the second monitor it doesn't let you change the background, and is black.

**Comment by fluxer** [comment]
Last time I checked (which was about 2-years ago) there were no issues with multi-monitor setup. I will look into it when I can.

**Comment by fluxer** [comment]
Fixed a related issue but from what I can tell the issue with the background was an issue even before the fork. I don't know version you used back then but the fork was based on v4.14.3. In any case, I will keep looking for issues related to multi-monitor setup including the one you mention.

**Comment by fluxer** [comment]
Closing due to https://github.com/fluxer/kde-workspace/commit/f058709ed6b21f4d4e8b9116f8535ee2ece5aa99. Delete your plasma-desktoprc config (`rm -vf ~/.katana/share/config/plasma-desktoprc`) and relog for the fix to take effect.

**Comment by erievs** [comment]
> Closing due to [fluxer/kde-workspace@f058709](https://github.com/fluxer/kde-workspace/commit/f058709ed6b21f4d4e8b9116f8535ee2ece5aa99). Delete your plasma-desktoprc config (`rm -vf ~/.katana/share/config/plasma-desktoprc`) and relog for the fix to take effect.

Uhh, I've tried that, it has seems that it broke Katana. There all I have is a black screen with my web browser, i'll try to reboot I guess. It also might be an issue relating to me having a 1920x1080 and a 1650x(idr).

**Comment by fluxer** [comment]
You probably did it while Katana is running, I should've mentioned that it should not be done from Katana session.

Anyway, works for me (with and without extra monitor) now it is up to you to get the fix.
